### ISSUE TITLE
Integrating Razorpay in django payment

### ISSUE THREAD

**Issue by AishwaryaPrabha** [mirumee/django-payments#189]
I was using saleor e-commerce and trying to integrate Razorpay payment gateway. I have tried many ways but could not get any help from anywhere. Can anyone help on how to integrate Razorpay?
[Link to Razorpay python sdk](https://github.com/razorpay/razorpay-python)

**Comment by oxalorg** [comment]
Although I haven't personally used `django-payments` with Razorpay (mostly because we needed more flexibility with handling and storing every single transaction state instead of mutating a single payment model), I'd recommend you check out how Stripe is integrated with django-payments and Razorpay would be very similar to it.

https://github.com/mirumee/django-payments/blob/master/payments/stripe/__init__.py

You'll have to modify `js/payments/stripe.js` with code to open the Razorpay Flash Checkout popup.

**Comment by AishwaryaPrabha** [comment]
@oxalorg - Thank you. Will check out the above same.

**Comment by NyanKiyoshi** [comment]
@AishwaryaPrabha you can install and enable this provider https://pypi.org/project/django-payments-razorpay/ combined with the patch at https://github.com/mirumee/saleor/pull/2550.

**Comment by dishantsethi** [comment]
Is someone working with this issue? Can I do the favour to integrate razorpay as a backend provider of Django-payments?

**Comment by Sachinjha469** [comment]
@dishantsethi That wud be great!

**Comment by NyanKiyoshi** [comment]
Additional backend providers have to be used third-party libraries, the owner the third-party library is in charge of maintaining its library. You can download django-payment-razorpay [here](https://pypi.org/project/django-payments-razorpay/).
